### PR TITLE
Fixed datapoint sending in JSON mode

### PR DESCRIPTION
**Pull request by sheremetat**

### CODE REVIEW

**Comment by cep21** [comment]
Can you amend the commit message to describe the problem more.  Was there some special case broken, or did it just never work?

**Comment by sheremetat** [comment]
4a1b0b6: There was a bug, when library crashed in json mode after adding new dimensions. Dimensions format in incoming data was incorrect
fc2b137: Invalid including of modules - fixed

**Comment by cep21** [comment]
Can you add the comment "There was a bug, when library crashed in json mode after adding new dimensions. Dimensions format in incoming data was incorrect" to the diff?

**Comment by cep21** [comment]
Hello,

Please run --amend on the commits you have and add the information above into the commit message.

For example, https://github.com/sheremetat/signalfx-ruby/commit/4a1b0b6fcee80284ef51e4c3ed1a0b10de08755f has a title but no body.  Please add the context you put into this diff into that comment and repush.  Let me know when you do.

Thanks!

**Pull request merged**
